name: built_redux_rx
version: 0.1.2
description:
   epics for built_redux
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/built_redux_rx
dependencies:
  built_redux: 
    git: https://github.com/guypeled76/built_redux
  built_value: '>=5.5.5 <7.0.0'
  rxdart: ^0.20.0

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.0
  built_value_generator: ^6.0.0
  build_web_compilers: ^1.0.0
  test: ^1.0.0

environment:
  sdk: '>=2.0.0-dev <3.0.0'
